version: 2

base_image: &base_image
  image: circleci/node:8.11

restore_dependencies: &restore_dependencies
  restore_cache:
    key: yarn-pacakges-{{ checksum "yarn.lock" }}

save_dependencies: &save_dependencies
  save_cache:
    key: yarn-pacakges-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

setup: &setup
  docker:
    - <<: *base_image

jobs:
  build:
    <<: *setup
    steps:
      - checkout
      - <<: *restore_dependencies
      - run: yarn install
      - run: yarn run babel
      - <<: *save_dependencies

  test:
    <<: *setup
    steps:
      - checkout
      - <<: *restore_dependencies
      - run: yarn install
      - run: yarn run babel
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
