version: 2
setup: &setup
  working_directory: ~/docbase-js
  docker:
    - image: circleci/node:12

jobs:
  build:
    <<: *setup
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/docbase-js/node_modules
      - run: yarn run build
      - save_cache:
          key: artifacts-{{ .Revision }}
          paths:
            - ~/docbase-js/dist
            - ~/docbase-js/lib
  test:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: artifacts-{{ .Revision }}
      - run: yarn run lint
      - run: yarn run run-s "test --collect-coverage" coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
