version: 2
base_image: &base_image
  image: circleci/node:8.11
setup: &setup
  working_directory: ~/docbase-js
  docker:
    - <<: *base_image
jobs:
  build:
    <<: *setup
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/docbase-js/node_modules
      - run:
          name: Build JavaScript files
          command: |
            yarn run babel
            yarn run build
      - save_cache:
          key: artifacts-{{ .Revision }}
          paths:
            - ~/docbase-js/dist
            - ~/docbase-js/lib
  test:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: artifacts-{{ .Revision }}
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
